name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./kanban-board

    - name: Build frontend
      run: npm run build --if-present
      working-directory: ./kanban-board

    - name: Run frontend tests
      run: npm test
      working-directory: ./kanban-board

  backend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install backend dependencies
      run: npm ci
      working-directory: ./back  # 假设你的后端代码在 back 目录

    - name: Build backend
      run: npm run build --if-present
      working-directory: ./back  # 如果你有构建命令

    - name: Run backend tests
      run: npm test
      working-directory: ./back
