name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: List files in default directory
      run: ls -la

    - name: List files in kanban-board directory
      run: ls -la
      working-directory: ./kanban-board

    - run: npm ci
      working-directory: ./kanban-board

    - run: npm run build --if-present
      working-directory: ./kanban-board

    - run: npm test
      working-directory: ./kanban-board
